version: '3.1'
services:
    db:
        image: mysql
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: testing
            MYSQL_USER: ana
            MYSQL_PASSWORD: ana
        ports:
          -  3307:3306








#version: '3.1'
#services:
#  db:
#    image: mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: test_db
#    ports:
#      - "3307:3306"
#    volumes:
#      - $HOME/Desktop/MySQL-Snippets/school.sql:/school.sql
