CREATE DATABASE IF NOT EXISTS Session_8;
USE Session_8;
#DROP DATABASE IF EXISTS Session_8;

CREATE TABLE IF NOT EXISTS Propuesta1DatosGeneracion (
	DATE_TIME DATETIME,
    PLANT_ID INT,
    SOURCER_KEY VARCHAR(16),
	DC_POWER DOUBLE,
	AC_POWER DOUBLE,
    DAILY_YIELD DOUBLE,
    TOTAL_YIELD DOUBLE
    #FOREIGN KEY (PLANT_ID) REFERENCES SensoresPropuesta1(PLANT_ID)
);
#DROP TABLE IF EXISTS Propuesta1DatosGeneracion;



CREATE TABLE IF NOT EXISTS Propuesta2DatosGeneracion (
	DATE_TIME DATETIME,
    PLANT_ID INT,
    SOURCER_KEY VARCHAR(16),
	DC_POWER DOUBLE,
	AC_POWER DOUBLE,
    DAILY_YIELD DOUBLE,
    TOTAL_YIELD DOUBLE
);
#DROP TABLE IF EXISTS Propuesta2DatosGeneracion;

CREATE TABLE IF NOT EXISTS SensoresPropuesta1 (
	DATE_TIME DATETIME,
    PLANT_ID INT PRIMARY KEY,
    SOURCE_KEY VARCHAR(16),
    AMBIENT_TEMPERATURE DOUBLE,
    MODULE_TEMPERATURE DOUBLE,
    IRRADIATION DOUBLE
);

CREATE TABLE IF NOT EXISTS SensoresPropuesta2 (
	DATE_TIME DATETIME,
    PLANT_ID INT PRIMARY KEY,
    SOURCE_KEY VARCHAR(16),
    AMBIENT_TEMPERATURE DOUBLE,
    MODULE_TEMPERATURE DOUBLE,
    IRRADIATION DOUBLE
    #FOREIGN KEY (PLANT_ID) REFERENCES Propuesta1DatosGeneracion(PLANT_ID) 
);

#INSERT INTO Propuesta2DatosGeneracion(DATE_TIME, PLANT_ID,SOURCE_KEY,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION) VALUES(FECHA, ENTERO,STRING,DOUBLE,DOUBLE....ETC);



